[package]
name = "ollama-web-app"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { git = "https://github.com/rwf2/Rocket" }
serde = "1.0.207"
serde_json = "1.0.124"
once_cell = "1.10.0"
ollama-lib = {path="ollama-lib"}
