[package]
name = "riscv32-bare-metal"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "s"
lto = true
panic = "abort"

[profile.dev]
panic = "abort"

[features]
qemu_bin = []
test_panic = []

[dependencies]
arrayvec = { version = "0.7", default-features = false }

[[bin]]
name = "riscv32-bare-metal"
path = "src/main.rs"
required-features = ["qemu_bin"]